### PR TITLE
Change configuration internals from constants to module attrs

### PR DESCRIPTION
**Pull request by ajsharp**
Re #26

### CODE REVIEW

**Comment by ajsharp** [comment]
@stevegraham I'm still resolving 2 spec failures related to webmock...

**Comment by stevegraham** [comment]
kewl. are the specs green now?

**Comment by ajsharp** [comment]
@stevegraham yup. Want to get this running on travis?

**Comment by stevegraham** [comment]
that's a good idea, but as it's 04:07 here I will take your word for it this time and merge!

**Comment by stevegraham** [comment]
nice work. thanks!

**Comment by ajsharp** [comment]
@stevegraham sounds good, thanks for the quick merge and ping-pong!

**Pull request merged**
