### PR TITLE
bypass auth for dev mode

### PR DESCRIPTION
**Pull request by markburns**

### CODE REVIEW

**Comment by markburns** [comment]
@stevegraham what about this one? objections? yay or nay?

**Comment by stevegraham** [comment]
No objections if you see a use for it. But do you think it's a sensible default?

**Comment by markburns** [comment]
To be honest, I can't remember the exact situation for this pull request, it was at that pusher/twilio etc hackathon.
Wasn't it something like the gem doesn't work in development mode? I thought you suggested switching off auth?

**Comment by stevegraham** [comment]
I mean should the checks be disabled in development by default or should it be a config?

**Comment by markburns** [comment]
Obviously, it makes sense for it to be config, but firstly I'm wondering if there was some other reason this doesn't work in dev? I.e. a different issue should be fixed. Or is it due to an issue at the Twilio end? I honestly can't remember the details.
Anyway, happy to make this configurable if you think the PR is useful, makes sense to do, and will merge it in.

**Comment by stevegraham** [comment]
It's because when you go to a protected path in the browser, the browser obviously doesn't send the twilio specific auth headers. It does work.

**Comment by markburns** [comment]
OK that makes sense. So yeah I'll make it configurable

**Pull request closed without merging**
